drone_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import check_password_hash
from drone_inventory.forms import UserLoginForm
from drone_inventory.models import User, db

# Imports for Flask Login
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data

            print(email, password)
            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'User-created')

            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')


    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data

            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in', 'auth-success')
                return redirect(url_for('site.profile'))
            
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

drone_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login.utils import login_required


"""
Note that in the above code, 
some arguments are specified when creating the Blueprint object. 
The first argument, "site", is the Blueprint’s name, 
which is used by Flask’s routing mechanism. 
The second argument, __name__, is the Blueprint’s import name, 
which Flask uses to locate the Blueprint’s resources.
"""

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')  

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Drone Inventory API</title>
</head>
<body>

        <!--NavBar Here-->
        <nav class="ct-nav">
            <div>
                <img src="../../static/images/Coding Drones Logo.png" alt="Coding Drones Logo">
            </div>
      
            <!--Nav Items-->
            <div>
                <ul id="horizontal-list">
                    <a href="{{ url_for('site.home') }}">
                        <li>The Coding Drones Project</li>
                    </a>
                    <a href="">
                        <li>Donate</li>
                    </a>

                    <!-- User Auth Check for SignIn/SignUp Nav Buttons -->
                    <!-- Line below should say "is_authenticated not isauthenticated" -->
                    {% if current_user.is_authenticated %}

                    <a href="{{ url_for('site.profile') }}">
                        <li>Profile</li>
                    </a>
                    
                    <a href="{{ url_for('auth.logout') }}">
                        <li>Log Out</li>
                    </a>

                    {% else %}
                    
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>
                    {% endif %}

                </ul>
            </div>
        </nav>
        <!--End of Nav-->
      
        {% block content %}
        {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"></script>
</body>
</html>

drone_inventory/templates/form.html
<!-- HTML Produced By the FlaskForm -->

<form action="" method="POST">
    {{ form.hidden_tag() }}

    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = 'Place Email Here...') }}
        </fieldset>
        <fieldset id="pasword-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = 'Place Password Here...') }}
        </fieldset>
    </div>

        <!-- Submit Button -->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}

</form>